# -*- coding: utf-8 -*-
"""octanet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bTpnQwQ1QvL-UMf5DpQbCy5NGQ1jd0fz
"""

class ATM:
    def __init__(self, user_id, pin, balance=1000):
        self.user_id = user_id
        self.pin = pin
        self.balance = balance

    def check_pin(self, entered_pin):
        return entered_pin == self.pin

    def check_balance(self):
        return self.balance

    def withdraw(self, amount):
        if 0 < amount <= self.balance:
            self.balance -= amount
            return amount
        return 0  # Insufficient balance or invalid amount

    def deposit(self, amount):
        if amount > 0:
            self.balance += amount
            return amount
        return 0  # Invalid amount

    def transfer(self, recipient, amount):
        if self.balance >= amount > 0:
            self.balance -= amount
            recipient.deposit(amount)
            return amount
        return 0  # Insufficient balance, invalid recipient, or invalid amount


def main():
    user_id = "12345"  # Replace with the actual user ID
    pin = "6789"  # Replace with the actual PIN

    user1 = ATM(user_id, pin)

    entered_pin = input("Enter your PIN: ")

    if user1.check_pin(entered_pin):
        print("PIN is correct. ATM functionality unlocked.")

        while True:
            print("1. Check Balance")
            print("2. Withdraw")
            print("3. Deposit")
            print("4. Transfer")
            print("5. Quit")

            choice = input("Select an option (1/2/3/4/5): ")

            if choice == "1":
                print("Balance: ${}".format(user1.check_balance()))
            elif choice == "2":
                amount = float(input("Enter the amount to withdraw: $"))
                withdrawn = user1.withdraw(amount)
                if withdrawn > 0:
                    print("Withdrawal successful. ${} withdrawn.".format(withdrawn))
                else:
                    print("Withdrawal failed. Insufficient balance or invalid amount.")
            elif choice == "3":
                amount = float(input("Enter the amount to deposit: $"))
                deposited = user1.deposit(amount)
                if deposited > 0:
                    print("Deposit successful. ${} deposited.".format(deposited))
                else:
                    print("Deposit failed. Invalid amount.")
            elif choice == "4":
                recipient_user_id = input("Enter recipient's User ID: ")
                recipient_pin = input("Enter recipient's PIN: ")
                recipient = ATM(recipient_user_id, recipient_pin)
                amount = float(input("Enter the amount to transfer: $"))
                transferred = user1.transfer(recipient, amount)
                if transferred > 0:
                    print("${} transferred to User ID: {}".format(transferred, recipient_user_id))
                else:
                    print("Transfer failed. Insufficient balance, invalid recipient, or invalid amount.")
            elif choice == "5":
                print("Thank you for using the ATM. Have a nice day!")
                break
            else:
                print("Invalid choice. Please select a valid option.")
    else:
        print("Invalid PIN. Access denied.")


if __name__ == "__main__":
    main()